### ISSUE TITLE
Handle StaticArrays?

### ISSUE THREAD

**Issue by gdalle** [adrhill/SparseConnectivityTracer.jl#144]
```julia
julia> using StaticArrays, SparseConnectivityTracer

julia> function f(x)
           y = SVector(x[1], x[2])
           return norm(y)
       end
f (generic function with 1 method)

julia> jacobian_sparsity(f, ones(2), TracerSparsityDetector())
ERROR: TypeError: non-boolean (SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int64, BitSet}}) used in boolean context
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/StaticArrays/MSJcA/src/linalg.jl:278 [inlined]
 [2] _norm
   @ ~/.julia/packages/StaticArrays/MSJcA/src/linalg.jl:266 [inlined]
 [3] norm
   @ ~/.julia/packages/StaticArrays/MSJcA/src/linalg.jl:265 [inlined]
 [4] f(x::Vector{SparseConnectivityTracer.GradientTracer{SparseConnectivityTracer.IndexSetGradientPattern{Int64, BitSet}}})
   @ Main ~/Work/GitHub/Julia/DifferentiationInterface.jl/DifferentiationInterface/test/playground.jl:56
 [5] trace_function(::Type{SparseConnectivityTracer.GradientTracer{…}}, f::typeof(f), x::Vector{Float64})
   @ SparseConnectivityTracer ~/.julia/packages/SparseConnectivityTracer/pVwOW/src/interface.jl:33
 [6] _jacobian_sparsity(f::Function, x::Vector{Float64}, ::Type{SparseConnectivityTracer.GradientTracer{…}})
   @ SparseConnectivityTracer ~/.julia/packages/SparseConnectivityTracer/pVwOW/src/interface.jl:59
 [7] jacobian_sparsity(f::Function, x::Vector{…}, ::TracerSparsityDetector{…})
   @ SparseConnectivityTracer ~/.julia/packages/SparseConnectivityTracer/pVwOW/src/adtypes.jl:49
 [8] top-level scope
   @ ~/Work/GitHub/Julia/DifferentiationInterface.jl/DifferentiationInterface/test/playground.jl:59
Some type information was truncated. Use `show(err)` to see complete types.
```
See https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/issues/247#issuecomment-2260558148

**Comment by adrhill** [comment]
Your liked comment points out the issue:
https://github.com/adrhill/SparseConnectivityTracer.jl/blob/ec44afc4b84cb1b6b7f234870776b4658a4987ac/src/overloads/arrays.jl#L72

We overload `norm(A::AbstractArray{<:AbstractTracer})`, which is less specific than StaticArrays' `norm(A:: StaticArray)` ([source](https://github.com/JuliaArrays/StaticArrays.jl/blob/431d57a4cc4f488144c9f5ff97ea388f5a4788b3/src/linalg.jl#L265)).

This is a general issue with array overloads since LinearAlgebra uses array-level types as traits for dispatch (e.g. `Symmetric`, `Hermitian`, ...). See also #133.

We could solve this problem by sticking our array overloads in a big loop over different array types.

**Comment by adrhill** [comment]
I guess we could start by supporting types form StaticArrays as well as common LinearAlgebra matrix types?

**Comment by gdalle** [comment]
Yeah but where does it stop?

**Comment by gdalle** [comment]
Also I don't want StaticArrays in the main dependencies so we might have to make the loop parametric and handle static types in a package extension.

**Comment by adrhill** [comment]
Closing, see discussion in #192.
