### ISSUE TITLE
More problems regarding `round`

### ISSUE THREAD

**Issue by SouthEndMusic** [adrhill/SparseConnectivityTracer.jl#164]
I did a quick test with the current main and I still have a problem with the function `round` where I want the return type to be an integer (and thus not depend smoothly on the input). `f(x) = Int(round(x))` doesn't work:

```
MethodError: no method matching Int64(::SparseConnectivityTracer.Dual{Float64, SparseConnectivityTracer.GradientTracer{…}})
```

Is that something you plan to support? Or should I resolve this in a different way? Still in the context of `DataInterpolations` by the way.

**Comment by SouthEndMusic** [comment]
This is the same problem as mentioned in https://github.com/adrhill/SparseConnectivityTracer.jl/issues/152#issuecomment-2286222243

**Comment by adrhill** [comment]
I'll take a look! Could you check whether `round(Int, x)` works?

**Comment by adrhill** [comment]
The problem in #152 is now part of our test suite, so I'd be surprised if it doesn't work:
https://github.com/adrhill/SparseConnectivityTracer.jl/blob/199899d842185df10b6da3ef05343c07cd9af382/test/test_gradient.jl#L222-L223

**Comment by adrhill** [comment]
If you want an explicit conversation for some reason, `convert(Int, round(x))` should work as well.

**Comment by SouthEndMusic** [comment]
Thanks. I'm running the unreleased `master` of `DataInterpolations` In which there are changes to the relevant code.

**Comment by SouthEndMusic** [comment]
The problem seems to be that `SparseConnectivityTracer.Dual{Int} <: Integer` doesn't hold, but that's probably by design

**Comment by SouthEndMusic** [comment]
Why is the instance of `SparseConnectivityTracer.Dual{Int}` created in the first place? Doesn't that indicate no connectivity anyway? Can't it just be an `Int`?

**Comment by adrhill** [comment]
> The problem seems to be that `SparseConnectivityTracer.Dual{Int} <: Integer` doesn't hold, but that's probably by design

If this was possible, it would indeed simplify things a lot. Unfortunately, Julia's type system doesn't allow it. 
`Dual` numbers are `Real`s and a thin wrapper around a primal number (in your case an `Int`) and a tracer which does the bookkeeping for the sparsity pattern:

https://github.com/adrhill/SparseConnectivityTracer.jl/blob/199899d842185df10b6da3ef05343c07cd9af382/src/tracers.jl#L103-L105

> Why is the instance of `SparseConnectivityTracer.Dual{Int}` created in the first place? Doesn't that indicate no connectivity anyway? Can't it just be an `Int`?

In the specific instance, we could (and I guess should?) indeed return an `Int`, since `round` gets rid of all first- and second-order derivative information.

More generally speaking, for things like `Int(mydual)` or `convert(Int, mydual)`, we are forced to return a `Dual` instead of an `Int`. This isn't optimal, since returning unexpected types leads to method invalidations and therefore increased compile times. But if we didn't do this, these type conversions would strip all derivative information by essentially removing the `tracer` part of the `Dual`.

This is somewhat of a design dilemma for us: do we (a) make the code run on most user-provided functions at the cost of invalidating some code or do we (b) throw a lot of errors and require users to rewrite their code such that it is compatible with SCT? For now, we aim for (a). 
Out of curiosity, I took a look at [ForwardDiff's approach to `Int(x)`](https://github.com/JuliaDiff/ForwardDiff.jl/blob/a286920bb5e401c8dc5d09589c9764d37cf5c6d2/src/dual.jl#L358-L365). It is more conservative and throws an `InexactError` if its derivative information is nonzero. Only if it is zero, it returns the primal value as an `Int`:

```Julia-repl
julia> using ForwardDiff

julia> ForwardDiff.derivative(x -> convert(Int, x), 1)
ERROR: InexactError: Int(Int64, Dual{ForwardDiff.Tag{var"#3#4", Int64}}(1,1))
Stacktrace:
 [1] Int64
   @ ~/.julia/packages/ForwardDiff/PcZ48/src/dual.jl:364 [inlined]
 [2] convert
   @ ./number.jl:7 [inlined]
 [3] #3
   @ ./REPL[3]:1 [inlined]
 [4] derivative(f::var"#3#4", x::Int64)
   @ ForwardDiff ~/.julia/packages/ForwardDiff/PcZ48/src/derivative.jl:14
 [5] top-level scope
   @ REPL[3]:1
```

Whether we stick with approach (a) and the invalidations or whether we move to approach (b) is something we should revisit before we tag a `v1.0` release. CC @gdalle.

**Comment by gdalle** [comment]
> More generally speaking, for things like `Int(mydual)` or `convert(Int, mydual)`, we are forced to return a  `Dual` instead of an `Int`. This isn't optimal, since returning unexpected types leads to method invalidations and therefore increased compile times. But if we didn't do this, these type conversions would strip all derivative information by essentially removing the tracer part of the `Dual`.

That's not true for `Int`, as discussed in #167, because `Int` conversion obliterates derivatives. However it is true e.g. for `convert(Float64, mydual)`.

**Comment by adrhill** [comment]
Let's discuss this in #167!

**Comment by adrhill** [comment]
To come back to the initial issue @SouthEndMusic: 
I'll add a conservative `Int(x::Dual)` overload à la ForwardDiff and return an `Int` iff the tracer is empty.

**Comment by gdalle** [comment]
Wait why? We can return an int in every case. And what you suggest sounds type unstable.

**Comment by adrhill** [comment]
Once again, let's discuss this in https://github.com/adrhill/SparseConnectivityTracer.jl/issues/167. ForwardDiff's approach I linked above is not type unstable: an `InexactError` is thrown when the derivative information would be lost.
