### ISSUE TITLE
Add CI benchmarking

### ISSUE THREAD

**Issue by adrhill** [adrhill/SparseConnectivityTracer.jl#54]

**Comment by gdalle** [comment]
For the benchmarks, all the test cases we have are very shallow: one layer of convolution, one iteration of the brusselator. It would make sense to add functions with a deeper computational graph, so that we observe the effects of e.g. recursive versus reallocating sets.

My suggestion for the prototypical Jacobian tracing benchmark would be iterated multiplication by random sparse matrices: `f(x) = A(p)^l * x` where `A(p) = sprand(n, n, p)`. We then have only three parameters to vary: `n`, `p` and `l`.

**Comment by adrhill** [comment]
Good point. We could also integrate the Brusselator ODE using [SimpleDiffEq.jl](https://github.com/SciML/SimpleDiffEq.jl#) and evaluate a [small LeNet5 CNN](https://github.com/FluxML/model-zoo/blob/72b98df811add2359ea9822d5c009b892b23d151/vision/conv_mnist/conv_mnist.jl#L41-L53).

**Comment by adrhill** [comment]
Primal value comparisons on `MaxPool` layers require local tracers, so the LeNet5 benchmark will have to wait for #57.
